# Reference:https://github.com/marketplace/actions/build-and-push-docker-images
name: Reporter Docker Image Build

on:
  push:
    branches: [ master, beta, develop ]

jobs:

  push_to_registries:
    name: Pushes Reporter Docker image to Dockerhub and Github Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thelusina/volt-ci-reporter
          dockerfile: "Dockerfile.reporter"
          tag_with_ref: true

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: brianlusina/volt-ci/volt-ci-reporter
        dockerfile: "Dockerfile.reporter"
        tag_with_ref: true